name: Compile, test and check the docs

on:
  workflow_call: 

jobs:

  check:
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: 8.8.1
            ghc-options: ""
            ignore-haddock: "true"
          - ghc: latest

    runs-on: ubuntu-latest

    steps:

      - uses: nikita-volkov/build-and-test-cabal-package.github-action@v1
        with:
          ghc: ${{matrix.ghc}}
          ghc-options: ${{matrix.ghc-options}}
          ignore-haddock: ${{matrix.ignore-haddock}}
